version: "3.7"

services:
  forticlient:
    build:
      context: .
      dockerfile: Dockerfile
    image: hybirdcorp/docker-forticlient
    environment:
      - VPNADDR=183.82.112.76:10443
      - VPNUSER=ganeshm
      - VPNPASS=ganeshm@123
      - VPNTIMEOUT=${VPNTIMEOUT:-10}
    network_mode: "host"
    privileged: true
